### ISSUE TITLE
Issue with Highly-Available Azure infrastructure Terraform deployment

### ISSUE THREAD

**Issue by fasalzaman** [microsoft/MCW-SAP-HANA-on-Azure#42] opened 2021-12-09 13:30 UTC
We are facing issues in terraform deployment in alternate environments. We were able to get the infrastructure deployed only on 70% of the instances. When we tested the terraform deployment we also face failures. We were only able to deploy 4 successful infrastructures out of the 6 total deployments.
Please find the issue details below :

While running the command "terraform_v2.sh apply template-ha1" , we are getting issues in some of the deployments. It is running forever and showing the same result in the terminal output. Please find the terminal output log below :
 We waited for more than 1 hour and the deployment was still running and showing the same status in the terminal.
Terminal output is:

module.hdb_node.azurerm_subnet_network_security_group_association.Associate-nsg-admin[0]: Still creating... [20m30s elapsed]
module.hdb_node.azurerm_network_interface.nics-dbnodes-admin[0]: Still creating... [20m30s elapsed]
module.hdb_node.azurerm_network_interface.nics-dbnodes-db[0]: Still creating... [20m0s elapsed]
module.hdb_node.azurerm_network_interface.nics-dbnodes-admin[1]: Still creating... [20m30s elapsed]
module.hdb_node.azurerm_subnet_network_security_group_association.Associate-nsg-db[0]: Still creating... [20m30s elapsed]
module.hdb_node.azurerm_network_security_rule.nsr-external-db[0]: Still creating... [20m30s elapsed]
module.hdb_node.azurerm_network_interface.nics-dbnodes-db[1]: Still creating... [20m30s elapsed]
module.hdb_node.azurerm_network_security_rule.nsr-internal-db[0]: Still creating... [20m10s elapsed]
module.common_infrastructure.azurerm_network_interface.iscsi[0]: Still creating... [20m40s elapsed]

**Comment by KitSkin** [comment] 2021-12-10 19:29
If these are only happening for a few and happening occasionally, it could be that there is a transitory issue as NSGs and NICs should only take a few minutes.  Cancelling a deployment in Azure and starting the deployment again results in an incremental deployment so any missing resources will be deployed, and settings on existing systems are updated.

**Comment by fasalzaman** [comment] 2021-12-16 15:39
We are still facing this issue with Highly available azure instance terraform deployment. The required extension inside the VMs are missing and on Hana instance deployment is running in to failure. Please find the error details below : 

Error : 

TASK [hana-system-replication : Ensure Secondary node is registered as secondary                                                                                                              in replication] ***
skipping: [10.101.1.10]
changed: [10.101.1.11]

TASK [hana-system-replication : Determine if HANA is running] ******************
skipping: [10.101.1.10]
ok: [10.101.1.11]

TASK [hana-system-replication : Ensure HANA is running] ************************
skipping: [10.101.1.10]


fatal: [10.101.1.11]: FAILED! => {"changed": true, "cmd": "source ~/.bashrc ; sa                                                                                                             pcontrol -nr 00 -function StartWait 2700 2\n", "delta": "0:45:01.773067", "end":                                                                                                              "2021-12-16 15:31:48.155847", "msg": "non-zero return code", "rc": 2, "start":                                                                                                              "2021-12-16 14:46:46.382780", "stderr": "tset: standard error: Inappropriate ioc                                                                                                             tl for device", "stderr_lines": ["tset: standard error: Inappropriate ioctl for                                                                                                              device"], "stdout": "\n16.12.2021 14:46:47\nStart\nOK\n\n16.12.2021 15:31:48\nSt                                                                                                             artWait\nFAIL: Timeout", "stdout_lines": ["", "16.12.2021 14:46:47", "Start", "O                                                                                                             K", "", "16.12.2021 15:31:48", "StartWait", "FAIL: Timeout"]}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
10.101.1.10                : ok=97   changed=39   unreachable=0    failed=0    s                                                                                                             kipped=46   rescued=0    ignored=0
10.101.1.11                : ok=96   changed=47   unreachable=0    failed=1    s                                                                                                             kipped=43   rescued=0    ignored=0
10.101.4.4                 : ok=11   changed=6    unreachable=0    failed=0    s                                                                                                             kipped=0    rescued=0    ignored=0
10.101.4.5                 : ok=11   changed=6    unreachable=0    failed=0    s                                                                                                             kipped=0    rescued=0    ignored=0
10.101.4.6                 : ok=11   changed=6    unreachable=0    failed=0    s                                                                                                             kipped=0    rescued=0    ignored=0
localhost                  : ok=13   changed=6    unreachable=0    failed=0    s                                                                                                             kipped=5    rescued=0    ignored=0

**Comment by DawnmarieDesJardins** [comment] 2021-12-17 18:49
@polichtm - Hi Marcin, please review & advise.

**Comment by polichtm** [comment] 2021-12-17 19:12
Hi Fasal,
Unfortunately we're not able to reproduce the issue - but we're aware that deployments might occasionally fail (that will be addressed longer term).
Is your deployment failing consistently - or are you seeing this failing from time to time?
rgds
Marcin

**Comment by DawnmarieDesJardins** [comment] 2022-03-10 18:34
Closing issue with merge of PR #45 - lab documents have been archived.

**Closed by DawnmarieDesJardins** 2022-03-10 18:34 UTC
